DELETE FROM Session_User;
DELETE FROM Facility_Modality;
DELETE FROM Class_daysOfWeek;
DELETE FROM Subscription;
DELETE FROM Session;
ALTER TABLE Class DROP FOREIGN KEY FKdy5ypn8cuocb7r7otfrfxsp3w;
DELETE FROM Class;
DELETE FROM ActiveClass;
DELETE FROM User;
DELETE FROM Facility;
DELETE FROM Modality;
ALTER TABLE Class ADD CONSTRAINT FKdy5ypn8cuocb7r7otfrfxsp3w FOREIGN KEY (currentactiveClass_ID) REFERENCES ActiveClass (ID);
INSERT INTO Modality (ID, NAME, MINDURATION, HOURPRICE) VALUES (1, 'Pilates', 50, 7);
INSERT INTO Modality (ID, NAME, MINDURATION, HOURPRICE) VALUES (2, 'Step', 45, 10);
INSERT INTO Modality (ID, NAME, MINDURATION, HOURPRICE) VALUES (3, 'GAP', 50, 10);
INSERT INTO Modality (ID, NAME, MINDURATION, HOURPRICE) VALUES (4, 'Indoor Cycling', 55, 10);
INSERT INTO Modality (ID, NAME, MINDURATION, HOURPRICE) VALUES (5, 'Hidroginastica', 45, 15);
INSERT INTO Facility (ID, CAPACITY, NAME, TYPE) VALUES (1, 20, 'Estudio 1', 'ESTUDIO');
INSERT INTO Facility (ID, CAPACITY ,NAME, TYPE) VALUES (2, 15, 'Estudio 2', 'ESTUDIO');
INSERT INTO Facility (ID, CAPACITY, NAME, TYPE) VALUES (3, 10, 'Sala de Bicicletas', 'SALA_DE_BICICLETAS');
INSERT INTO Facility (ID, CAPACITY, NAME, TYPE) VALUES (4, 20, 'Piscina 25', 'PISCINA');
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (1,1);
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (1,2);
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (1,3);
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (2,1);
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (3,4);
INSERT INTO Facility_Modality (Facility_ID, validModalities_ID) VALUES (4,5);
INSERT INTO User (ID, UserID, NAME, NIF, DEBT) VALUES (1, 1, 'Ulisses', 223842389, 0);
INSERT INTO User (ID, UserID, NAME, NIF, DEBT) VALUES (2, 2, 'David', 256039682, 0);
INSERT INTO User (ID, UserID, NAME, NIF, DEBT) VALUES (3, 3, 'Teresa', 269901841, 0);
INSERT INTO User (ID, UserID, NAME, NIF, DEBT) VALUES (4, 4, 'Querubim', 197672337, 0);
INSERT INTO User (ID, UserID, NAME, NIF, DEBT) VALUES (5, 5, 'Cicero', 221057552, 0);